#!/bin/bash

cp -rf . ~/.bashellrc
printf "
if [ -f ~/.bashellrc/bashrc ]; then
    . ~/.bashellrc/bashrc
fi
" >> ~/.bashrc
cp ~/gitconfig ./gitconfig.bk
cp ./gitconfig ~/.gitconfig
cp ~/.gitignore_global ./gitignore_global.bk
cp ./gitignore_global ~/.gitignore_global

