#!/bin/bash

cp -rf . ~/.bashellrc
printf "
if [ -f ~/.bashellrc/bashrc ]; then
    . ~/.bashellrc/bashrc
fi
" >> ~/.bashrc
if [ -f ~/.gitconfig ]; then
    cp ~/.gitconfig ./gitconfig.bk
fi

cp ./gitconfig ~/.gitconfig

if [ -f ~/.gitignore_global ]; then
    cp ~/.gitignore_global ./gitignore_global.bk
fi
cp ./gitignore_global ~/.gitignore_global

