#!/bin/bash


if [ -f ~/.gitconfig ]; then
    cp ~/.gitconfig ./gitconfig.bk
fi

cp ./gitconfig ~/.gitconfig

if [ -f ~/.gitignore_global ]; then
    cp ~/.gitignore_global ./gitignore_global.bk
fi

cp ./gitignore_global ~/.gitignore_global

